[package]
name = "magic-wormhole"
version = "0.0.3-alpha.0"
authors = ["Brian Warner <warner@lothar.com>"]
license = "MIT"
homepage = "http://magic-wormhole.io/"
repository = "https://github.com/warner/magic-wormhole.rs"
edition = "2018"
description = "Get things from one computer to another, safely"
readme = "README.md"

# the MSRV is rust-1.33.0, due to (at least) percent-encoding-2.1.0 using
# local variables in a const fn, which was unstable in rust-1.32.0

[badges]
travis-ci = { repository = "warner/magic-wormhole.rs" }

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
chacha20poly1305 = { version = "0.1", features = ["xchacha20poly1305"]}
spake2 = "0.2.0"
sha2 = "0.8"
hkdf = "0.8.0"
hex = "0.3"
rand = "0.7"
regex = "1.0"
log = "0.4"

# for "io_blocking" feature
ws = { version = "0.9", optional = true }
url = { version = "2.1", optional = true }

# for "io_tokio" feature
websocket = { version = "0.23", optional = true }
futures = { version = "0.1", optional = true }
tokio-core = { version = "0.1", optional = true }

# for "bin" feature
clap = { version = "2.32", optional = true}

[dev-dependencies]
ws = "0.9"
url = "2.1"
rustyline = "5.0"
parking_lot = {version = "0.9", features = ["deadlock_detection"]}
hex = "0.3"
env_logger = "0.6"

[features]
default = ["io-blocking", "io-tokio", "bin"]
io-blocking = ["ws", "url"]
io-tokio = ["websocket", "futures", "tokio-core"]
bin = ["clap"]

[[bin]]
name = "wormhole"
path = "src/bin/main.rs"
required-features = ["io-blocking"]

[profile.release]
overflow-checks = true
